var hljs = require('./highlight')

hljs.registerLanguage('cpp', require('./languages/cpp'))
hljs.registerLanguage('xml', require('./languages/xml'))
hljs.registerLanguage('bash', require('./languages/bash'))
hljs.registerLanguage('basic', require('./languages/basic'))
hljs.registerLanguage('cs', require('./languages/cs'))
hljs.registerLanguage('css', require('./languages/css'))
hljs.registerLanguage('ruby', require('./languages/ruby'))
hljs.registerLanguage('erb', require('./languages/erb'))
hljs.registerLanguage('go', require('./languages/go'))
hljs.registerLanguage('haml', require('./languages/haml'))
hljs.registerLanguage('java', require('./languages/java'))
hljs.registerLanguage('javascript', require('./languages/javascript'))
hljs.registerLanguage('json', require('./languages/json'))
hljs.registerLanguage('php', require('./languages/php'))
hljs.registerLanguage('python', require('./languages/python'))
hljs.registerLanguage('console', require('./languages/shell'))
hljs.registerLanguage('sql', require('./languages/sql'))
hljs.registerLanguage('yaml', require('./languages/yaml'))
hljs.registerLanguage('vim', require('./languages/vim'))

module.exports = hljs
